# Generated by Django 4.2.2 on 2023-07-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200118_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
